import json
import yaml


def _yaml_get_pairs(y) -> dict:
    """ gets <mac: logger_name> pairs """
    try:
        with open(y) as f:
            data = yaml.load(f, Loader=yaml.FullLoader)
            return data
    except TypeError as te:
        print('error yaml_get_macs')
        raise te


def _lower_macs(m):
    return {k.lower(): v for k, v in m.items()}


def _check_macs(pairs):
    rv = True
    for i in pairs.keys():
        rv = rv and len(i) == 17
        if not rv:
            e = 'bad mac {}'.format(i)
            raise ValueError(e)


def yaml_load_pairs(f):
    """ gets and checks <mac: logger_name> pairs """
    try:
        f = f[0]
        if not f.endswith('.yml'):
            return
        m = _yaml_get_pairs(f)
        _check_macs(m)
        m = _lower_macs(m)
        return m
    except (TypeError, ValueError):
        return None


def gen_ddh_json_content(known, v, f_t):
    """ generates ddh.json content """
    data = dict()
    s = 'auto-generated by DDH setup tab, do not edit'
    data['comment'] = s
    data['db_logger_macs'] = known
    data['ship_name'] = v
    data['forget_time'] = f_t
    data['metrics'] = [["DOS", "DOT"], ["T", "P"]]
    data['span_dict'] = {
            "h": [4, 15, 60, "%H:%M", 1],
            "d": [48, 30, 1440, "%H", 2],
            "w": [14, 720, 10080, "%m/%d", 2],
            "m": [31, 1440, 43800, "%d", 1],
            "y": [12, 43800, 525600, "%b %y", 1]
    }
    data['units'] = 'F'
    data['hci_if'] = 0
    return json.dumps(data, indent=4)
