# To build this:
# $ sudo docker build -t ddh:latest .


FROM arm32v7/ubuntu:18.04
MAINTAINER joaquim@lowellinstruments.com


# timezone will be set when running container
RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN apt-get install -y apt-utils python3 python3-pip \
    wget git cython3 python3-numpy \
    libpq-dev python3-dev nano libatlas3-base \
    libglib2.0-dev libgdal-dev bluez x11-apps \
    libgl1-mesa-glx python3-pyqt5 sudo wireless-tools \
    python3-pandas python3-matplotlib python3-h5py \
    iputils-ping iproute2 ifmetric


# todo: git clone DDH to a temp dir, w/ proper MAT branch
# mv everything cloned into /ddh
