# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ble_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tabs(object):
    def setupUi(self, tabs):
        tabs.setObjectName("tabs")
        tabs.setWindowModality(QtCore.Qt.NonModal)
        tabs.setEnabled(True)
        tabs.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tabs.sizePolicy().hasHeightForWidth())
        tabs.setSizePolicy(sizePolicy)
        tabs.setMinimumSize(QtCore.QSize(800, 480))
        tabs.setMaximumSize(QtCore.QSize(800, 480))
        font = QtGui.QFont()
        font.setPointSize(12)
        tabs.setFont(font)
        tabs.setTabPosition(QtWidgets.QTabWidget.North)
        tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        tabs.setIconSize(QtCore.QSize(24, 24))
        tabs.setUsesScrollButtons(False)
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setEnabled(True)
        self.tab_info.setObjectName("tab_info")
        self.layoutWidget = QtWidgets.QWidget(self.tab_info)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 230, 701, 121))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_time = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_time.setFont(font)
        self.lbl_time.setScaledContents(False)
        self.lbl_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_time.setObjectName("lbl_time")
        self.horizontalLayout.addWidget(self.lbl_time)
        self.lbl_sync = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_sync.setFont(font)
        self.lbl_sync.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sync.setObjectName("lbl_sync")
        self.horizontalLayout.addWidget(self.lbl_sync)
        self.lbl_boatname = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_boatname.setFont(font)
        self.lbl_boatname.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_boatname.setObjectName("lbl_boatname")
        self.horizontalLayout.addWidget(self.lbl_boatname)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_info)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 40, 704, 202))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(25)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img_time = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_time.sizePolicy().hasHeightForWidth())
        self.img_time.setSizePolicy(sizePolicy)
        self.img_time.setMaximumSize(QtCore.QSize(200, 200))
        self.img_time.setText("")
        self.img_time.setPixmap(QtGui.QPixmap("res/img_datetime.png"))
        self.img_time.setScaledContents(True)
        self.img_time.setObjectName("img_time")
        self.horizontalLayout_2.addWidget(self.img_time)
        self.img_sync = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_sync.sizePolicy().hasHeightForWidth())
        self.img_sync.setSizePolicy(sizePolicy)
        self.img_sync.setMaximumSize(QtCore.QSize(200, 200))
        self.img_sync.setText("")
        self.img_sync.setPixmap(QtGui.QPixmap("res/img_sync.png"))
        self.img_sync.setScaledContents(True)
        self.img_sync.setObjectName("img_sync")
        self.horizontalLayout_2.addWidget(self.img_sync)
        self.img_boat = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_boat.sizePolicy().hasHeightForWidth())
        self.img_boat.setSizePolicy(sizePolicy)
        self.img_boat.setMaximumSize(QtCore.QSize(200, 200))
        self.img_boat.setText("")
        self.img_boat.setPixmap(QtGui.QPixmap("res/img_boatname.png"))
        self.img_boat.setScaledContents(True)
        self.img_boat.setObjectName("img_boat")
        self.horizontalLayout_2.addWidget(self.img_boat)
        self.lbl_error = QtWidgets.QLabel(self.tab_info)
        self.lbl_error.setGeometry(QtCore.QRect(50, 360, 681, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_error.setFont(font)
        self.lbl_error.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_error.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_error.setObjectName("lbl_error")
        tabs.addTab(self.tab_info, "")
        self.tab_dl = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_dl.sizePolicy().hasHeightForWidth())
        self.tab_dl.setSizePolicy(sizePolicy)
        self.tab_dl.setObjectName("tab_dl")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_dl)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 771, 381))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.vl_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.vl_2.setContentsMargins(0, 0, 0, 0)
        self.vl_2.setSpacing(0)
        self.vl_2.setObjectName("vl_2")
        self.lbl_dl_status_1 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_dl_status_1.setFont(font)
        self.lbl_dl_status_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dl_status_1.setObjectName("lbl_dl_status_1")
        self.vl_2.addWidget(self.lbl_dl_status_1)
        self.lbl_dl_status_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_dl_status_2.setFont(font)
        self.lbl_dl_status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dl_status_2.setObjectName("lbl_dl_status_2")
        self.vl_2.addWidget(self.lbl_dl_status_2)
        self.lbl_dl_status_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_dl_status_3.setFont(font)
        self.lbl_dl_status_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dl_status_3.setObjectName("lbl_dl_status_3")
        self.vl_2.addWidget(self.lbl_dl_status_3)
        self.lbl_busy_dl = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_busy_dl.setFont(font)
        self.lbl_busy_dl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_busy_dl.setObjectName("lbl_busy_dl")
        self.vl_2.addWidget(self.lbl_busy_dl)
        self.bar_dl = QtWidgets.QProgressBar(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar_dl.sizePolicy().hasHeightForWidth())
        self.bar_dl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bar_dl.setFont(font)
        self.bar_dl.setProperty("value", 0)
        self.bar_dl.setObjectName("bar_dl")
        self.vl_2.addWidget(self.bar_dl)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/icon_dl.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tabs.addTab(self.tab_dl, icon, "")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_plot)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 771, 391))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.vl_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.vl_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vl_3.setContentsMargins(0, 0, 0, 0)
        self.vl_3.setSpacing(0)
        self.vl_3.setObjectName("vl_3")
        self.lbl_busy_plot = QtWidgets.QLabel(self.tab_plot)
        self.lbl_busy_plot.setGeometry(QtCore.QRect(10, 190, 771, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_busy_plot.setFont(font)
        self.lbl_busy_plot.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_busy_plot.setObjectName("lbl_busy_plot")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../res/icon_graph.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tabs.addTab(self.tab_plot, icon1, "")

        self.retranslateUi(tabs)
        tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tabs)

    def retranslateUi(self, tabs):
        _translate = QtCore.QCoreApplication.translate
        tabs.setWindowTitle(_translate("tabs", "Lowell Instruments\' BLE GUI"))
        self.lbl_time.setText(_translate("tabs", "<time>"))
        self.lbl_sync.setText(_translate("tabs", "<sync>"))
        self.lbl_boatname.setText(_translate("tabs", "<boat name>"))
        self.lbl_error.setText(_translate("tabs", "label_error"))
        tabs.setTabText(tabs.indexOf(self.tab_info), _translate("tabs", " Information"))
        self.lbl_dl_status_1.setText(_translate("tabs", "..."))
        self.lbl_dl_status_2.setText(_translate("tabs", "..."))
        self.lbl_dl_status_3.setText(_translate("tabs", "..."))
        self.lbl_busy_dl.setText(_translate("tabs", "..."))
        tabs.setTabText(tabs.indexOf(self.tab_dl), _translate("tabs", " Download"))
        self.lbl_busy_plot.setText(_translate("tabs", "..."))
        tabs.setTabText(tabs.indexOf(self.tab_plot), _translate("tabs", " Plots"))


