# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ble_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tabs(object):
    def setupUi(self, tabs):
        tabs.setObjectName("tabs")
        tabs.setWindowModality(QtCore.Qt.NonModal)
        tabs.setEnabled(True)
        tabs.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tabs.sizePolicy().hasHeightForWidth())
        tabs.setSizePolicy(sizePolicy)
        tabs.setMinimumSize(QtCore.QSize(800, 480))
        tabs.setMaximumSize(QtCore.QSize(800, 480))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setKerning(False)
        tabs.setFont(font)
        tabs.setWindowTitle("")
        tabs.setTabPosition(QtWidgets.QTabWidget.North)
        tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        tabs.setIconSize(QtCore.QSize(24, 24))
        tabs.setUsesScrollButtons(False)
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setEnabled(True)
        self.tab_info.setObjectName("tab_info")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_info)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(410, 20, 361, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget_2.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget_2.setSizePolicy(sizePolicy)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bar_dl = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bar_dl.sizePolicy().hasHeightForWidth())
        self.bar_dl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(False)
        self.bar_dl.setFont(font)
        self.bar_dl.setProperty("value", 0)
        self.bar_dl.setAlignment(QtCore.Qt.AlignCenter)
        self.bar_dl.setObjectName("bar_dl")
        self.gridLayout_3.addWidget(self.bar_dl, 2, 2, 1, 1)
        self.lbl_ble = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.lbl_ble.sizePolicy().hasHeightForWidth())
        self.lbl_ble.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lbl_ble.setFont(font)
        self.lbl_ble.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ble.setObjectName("lbl_ble")
        self.gridLayout_3.addWidget(self.lbl_ble, 0, 2, 2, 1)
        self.img_ble = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.img_ble.sizePolicy().hasHeightForWidth())
        self.img_ble.setSizePolicy(sizePolicy)
        self.img_ble.setText("")
        self.img_ble.setPixmap(QtGui.QPixmap("res/img_blue.png"))
        self.img_ble.setScaledContents(True)
        self.img_ble.setObjectName("img_ble")
        self.gridLayout_3.addWidget(self.img_ble, 0, 0, 3, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 3, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_info)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(30, 160, 361, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget_4.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget_4.setSizePolicy(sizePolicy)
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.img_sync = QtWidgets.QLabel(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_sync.sizePolicy().hasHeightForWidth())
        self.img_sync.setSizePolicy(sizePolicy)
        self.img_sync.setText("")
        self.img_sync.setPixmap(QtGui.QPixmap("res/img_sync.png"))
        self.img_sync.setScaledContents(True)
        self.img_sync.setObjectName("img_sync")
        self.gridLayout_5.addWidget(self.img_sync, 0, 0, 1, 1)
        self.lbl_internet = QtWidgets.QLabel(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_internet.sizePolicy().hasHeightForWidth())
        self.lbl_internet.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lbl_internet.setFont(font)
        self.lbl_internet.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_internet.setObjectName("lbl_internet")
        self.gridLayout_5.addWidget(self.lbl_internet, 0, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_info)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 361, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget.setSizePolicy(sizePolicy)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_clock_time = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_clock_time.sizePolicy().hasHeightForWidth())
        self.lbl_clock_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lbl_clock_time.setFont(font)
        self.lbl_clock_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_clock_time.setObjectName("lbl_clock_time")
        self.gridLayout.addWidget(self.lbl_clock_time, 1, 1, 1, 1)
        self.img_time = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_time.sizePolicy().hasHeightForWidth())
        self.img_time.setSizePolicy(sizePolicy)
        self.img_time.setText("")
        self.img_time.setPixmap(QtGui.QPixmap("res/img_datetime.png"))
        self.img_time.setScaledContents(True)
        self.img_time.setObjectName("img_time")
        self.gridLayout.addWidget(self.img_time, 0, 0, 2, 1)
        self.lbl_clock_sync = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_clock_sync.sizePolicy().hasHeightForWidth())
        self.lbl_clock_sync.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lbl_clock_sync.setFont(font)
        self.lbl_clock_sync.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_clock_sync.setObjectName("lbl_clock_sync")
        self.gridLayout.addWidget(self.lbl_clock_sync, 0, 1, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_info)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(30, 300, 361, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget_6.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget_6.setSizePolicy(sizePolicy)
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.img_latnlon = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_latnlon.sizePolicy().hasHeightForWidth())
        self.img_latnlon.setSizePolicy(sizePolicy)
        self.img_latnlon.setText("")
        self.img_latnlon.setPixmap(QtGui.QPixmap("res/img_latnlon.png"))
        self.img_latnlon.setScaledContents(True)
        self.img_latnlon.setObjectName("img_latnlon")
        self.gridLayout_7.addWidget(self.img_latnlon, 0, 0, 1, 1)
        self.lbl_gps = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_gps.sizePolicy().hasHeightForWidth())
        self.lbl_gps.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lbl_gps.setFont(font)
        self.lbl_gps.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gps.setObjectName("lbl_gps")
        self.gridLayout_7.addWidget(self.lbl_gps, 0, 1, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_info)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(410, 160, 361, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget_7.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget_7.setSizePolicy(sizePolicy)
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lbl_out = QtWidgets.QLabel(self.gridLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_out.sizePolicy().hasHeightForWidth())
        self.lbl_out.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lbl_out.setFont(font)
        self.lbl_out.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_out.setObjectName("lbl_out")
        self.gridLayout_8.addWidget(self.lbl_out, 0, 1, 1, 1)
        self.img_output = QtWidgets.QLabel(self.gridLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.img_output.sizePolicy().hasHeightForWidth())
        self.img_output.setSizePolicy(sizePolicy)
        self.img_output.setText("")
        self.img_output.setPixmap(QtGui.QPixmap("res/img_wait_black.png"))
        self.img_output.setScaledContents(True)
        self.img_output.setObjectName("img_output")
        self.gridLayout_8.addWidget(self.img_output, 0, 0, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab_info)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(410, 300, 361, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget_8.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget_8.setSizePolicy(sizePolicy)
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lbl_dbg = QtWidgets.QLabel(self.gridLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_dbg.sizePolicy().hasHeightForWidth())
        self.lbl_dbg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setKerning(False)
        self.lbl_dbg.setFont(font)
        self.lbl_dbg.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_dbg.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dbg.setWordWrap(True)
        self.lbl_dbg.setObjectName("lbl_dbg")
        self.gridLayout_9.addWidget(self.lbl_dbg, 0, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/icon_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tabs.addTab(self.tab_info, icon, "")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_plot)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 0, 771, 431))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.vl_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.vl_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vl_3.setContentsMargins(0, 0, 0, 0)
        self.vl_3.setSpacing(0)
        self.vl_3.setObjectName("vl_3")
        self.lbl_plt_msg = QtWidgets.QLabel(self.tab_plot)
        self.lbl_plt_msg.setGeometry(QtCore.QRect(120, 280, 551, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_plt_msg.setFont(font)
        self.lbl_plt_msg.setStyleSheet("background: lightblue;")
        self.lbl_plt_msg.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_plt_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_plt_msg.setWordWrap(True)
        self.lbl_plt_msg.setObjectName("lbl_plt_msg")
        self.lbl_plt_bsy = QtWidgets.QLabel(self.tab_plot)
        self.lbl_plt_bsy.setGeometry(QtCore.QRect(345, 130, 100, 101))
        font = QtGui.QFont()
        font.setPointSize(64)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lbl_plt_bsy.setFont(font)
        self.lbl_plt_bsy.setStyleSheet("")
        self.lbl_plt_bsy.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_plt_bsy.setTextFormat(QtCore.Qt.RichText)
        self.lbl_plt_bsy.setScaledContents(True)
        self.lbl_plt_bsy.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_plt_bsy.setWordWrap(True)
        self.lbl_plt_bsy.setObjectName("lbl_plt_bsy")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/icon_graph.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tabs.addTab(self.tab_plot, icon1, "")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_log)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.img_boat = QtWidgets.QLabel(self.tab_log)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_boat.sizePolicy().hasHeightForWidth())
        self.img_boat.setSizePolicy(sizePolicy)
        self.img_boat.setText("")
        self.img_boat.setPixmap(QtGui.QPixmap("res/img_boatname.png"))
        self.img_boat.setScaledContents(True)
        self.img_boat.setObjectName("img_boat")
        self.horizontalLayout_2.addWidget(self.img_boat)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.lbl_boatname = QtWidgets.QLabel(self.tab_log)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_boatname.sizePolicy().hasHeightForWidth())
        self.lbl_boatname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(False)
        self.lbl_boatname.setFont(font)
        self.lbl_boatname.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_boatname.setObjectName("lbl_boatname")
        self.horizontalLayout_2.addWidget(self.lbl_boatname)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.lbl_ver = QtWidgets.QLabel(self.tab_log)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_ver.setFont(font)
        self.lbl_ver.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ver.setObjectName("lbl_ver")
        self.horizontalLayout_2.addWidget(self.lbl_ver)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(3, 4)
        self.horizontalLayout_2.setStretch(5, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tbl_his = QtWidgets.QTableWidget(self.tab_log)
        self.tbl_his.setEnabled(True)
        self.tbl_his.setStyleSheet("font: 19pt \"Ubuntu\";")
        self.tbl_his.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tbl_his.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_his.setShowGrid(True)
        self.tbl_his.setRowCount(5)
        self.tbl_his.setColumnCount(3)
        self.tbl_his.setObjectName("tbl_his")
        self.tbl_his.horizontalHeader().setDefaultSectionSize(210)
        self.tbl_his.horizontalHeader().setHighlightSections(False)
        self.tbl_his.horizontalHeader().setMinimumSectionSize(80)
        self.tbl_his.verticalHeader().setVisible(False)
        self.tbl_his.verticalHeader().setDefaultSectionSize(36)
        self.tbl_his.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_4.addWidget(self.tbl_his)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(2, 6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/icon_history.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tabs.addTab(self.tab_log, icon2, "")

        self.retranslateUi(tabs)
        tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(tabs)

    def retranslateUi(self, tabs):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_ble.setText(_translate("tabs", "<ble>"))
        self.lbl_internet.setText(_translate("tabs", "<internet>"))
        self.lbl_clock_time.setText(_translate("tabs", "<clocktime>"))
        self.lbl_clock_sync.setText(_translate("tabs", "<clocksync>"))
        self.lbl_gps.setText(_translate("tabs", "<latnlon>"))
        self.lbl_out.setText(_translate("tabs", "Initializing"))
        self.lbl_dbg.setText(_translate("tabs", "No issues found"))
        tabs.setTabText(tabs.indexOf(self.tab_info), _translate("tabs", " Information"))
        self.lbl_plt_msg.setText(_translate("tabs", "msg_plt"))
        self.lbl_plt_bsy.setText(_translate("tabs", "···"))
        tabs.setTabText(tabs.indexOf(self.tab_plot), _translate("tabs", " Plots"))
        self.lbl_boatname.setText(_translate("tabs", "<boatname>"))
        self.lbl_ver.setText(_translate("tabs", "<version>"))
        tabs.setTabText(tabs.indexOf(self.tab_log), _translate("tabs", " History"))
