# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ble_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tabs(object):
    def setupUi(self, tabs):
        tabs.setObjectName("tabs")
        tabs.setWindowModality(QtCore.Qt.NonModal)
        tabs.setEnabled(True)
        tabs.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tabs.sizePolicy().hasHeightForWidth())
        tabs.setSizePolicy(sizePolicy)
        tabs.setMinimumSize(QtCore.QSize(800, 480))
        tabs.setMaximumSize(QtCore.QSize(800, 480))
        font = QtGui.QFont()
        font.setPointSize(12)
        tabs.setFont(font)
        tabs.setTabPosition(QtWidgets.QTabWidget.North)
        tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        tabs.setIconSize(QtCore.QSize(24, 24))
        tabs.setUsesScrollButtons(False)
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setEnabled(True)
        self.tab_info.setObjectName("tab_info")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_info)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(460, 20, 301, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget_2.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget_2.setSizePolicy(sizePolicy)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_ble_short = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.lbl_ble_short.sizePolicy().hasHeightForWidth())
        self.lbl_ble_short.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_ble_short.setFont(font)
        self.lbl_ble_short.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ble_short.setObjectName("lbl_ble_short")
        self.gridLayout_3.addWidget(self.lbl_ble_short, 0, 1, 1, 1)
        self.bar_dl = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.bar_dl.sizePolicy().hasHeightForWidth())
        self.bar_dl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bar_dl.setFont(font)
        self.bar_dl.setProperty("value", 0)
        self.bar_dl.setAlignment(QtCore.Qt.AlignCenter)
        self.bar_dl.setObjectName("bar_dl")
        self.gridLayout_3.addWidget(self.bar_dl, 2, 0, 1, 2)
        self.img_ble = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.img_ble.sizePolicy().hasHeightForWidth())
        self.img_ble.setSizePolicy(sizePolicy)
        self.img_ble.setText("")
        self.img_ble.setPixmap(QtGui.QPixmap("res/img_blue.png"))
        self.img_ble.setScaledContents(True)
        self.img_ble.setObjectName("img_ble")
        self.gridLayout_3.addWidget(self.img_ble, 0, 0, 1, 1)
        self.lbl_ble_long = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.lbl_ble_long.sizePolicy().hasHeightForWidth())
        self.lbl_ble_long.setSizePolicy(sizePolicy)
        self.lbl_ble_long.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ble_long.setObjectName("lbl_ble_long")
        self.gridLayout_3.addWidget(self.lbl_ble_long, 3, 0, 1, 2)
        self.spacer = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.spacer.setMaximumSize(QtCore.QSize(16777215, 10))
        self.spacer.setText("")
        self.spacer.setObjectName("spacer")
        self.gridLayout_3.addWidget(self.spacer, 1, 0, 1, 2)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_info)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 411, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget_3.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget_3.setSizePolicy(sizePolicy)
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_boatname = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_boatname.sizePolicy().hasHeightForWidth())
        self.lbl_boatname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_boatname.setFont(font)
        self.lbl_boatname.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_boatname.setObjectName("lbl_boatname")
        self.gridLayout_4.addWidget(self.lbl_boatname, 0, 1, 1, 1)
        self.img_boat = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_boat.sizePolicy().hasHeightForWidth())
        self.img_boat.setSizePolicy(sizePolicy)
        self.img_boat.setText("")
        self.img_boat.setPixmap(QtGui.QPixmap("res/img_boatname.png"))
        self.img_boat.setScaledContents(True)
        self.img_boat.setObjectName("img_boat")
        self.gridLayout_4.addWidget(self.img_boat, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_info)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(30, 160, 411, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget_4.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget_4.setSizePolicy(sizePolicy)
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.img_sync = QtWidgets.QLabel(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_sync.sizePolicy().hasHeightForWidth())
        self.img_sync.setSizePolicy(sizePolicy)
        self.img_sync.setText("")
        self.img_sync.setPixmap(QtGui.QPixmap("res/img_sync.png"))
        self.img_sync.setScaledContents(True)
        self.img_sync.setObjectName("img_sync")
        self.gridLayout_5.addWidget(self.img_sync, 0, 0, 1, 1)
        self.lbl_internet = QtWidgets.QLabel(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_internet.sizePolicy().hasHeightForWidth())
        self.lbl_internet.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_internet.setFont(font)
        self.lbl_internet.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_internet.setObjectName("lbl_internet")
        self.gridLayout_5.addWidget(self.lbl_internet, 0, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_info)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 300, 411, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget.setSizePolicy(sizePolicy)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_clock_time = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_clock_time.sizePolicy().hasHeightForWidth())
        self.lbl_clock_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_clock_time.setFont(font)
        self.lbl_clock_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_clock_time.setObjectName("lbl_clock_time")
        self.gridLayout.addWidget(self.lbl_clock_time, 1, 1, 1, 1)
        self.img_time = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_time.sizePolicy().hasHeightForWidth())
        self.img_time.setSizePolicy(sizePolicy)
        self.img_time.setText("")
        self.img_time.setPixmap(QtGui.QPixmap("res/img_datetime.png"))
        self.img_time.setScaledContents(True)
        self.img_time.setObjectName("img_time")
        self.gridLayout.addWidget(self.img_time, 0, 0, 2, 1)
        self.lbl_clock_sync = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_clock_sync.sizePolicy().hasHeightForWidth())
        self.lbl_clock_sync.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_clock_sync.setFont(font)
        self.lbl_clock_sync.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_clock_sync.setObjectName("lbl_clock_sync")
        self.gridLayout.addWidget(self.lbl_clock_sync, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_info)
        self.label_13.setGeometry(QtCore.QRect(740, 250, 30, 116))
        self.label_13.setMinimumSize(QtCore.QSize(30, 0))
        self.label_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_13.setText("")
        self.label_13.setScaledContents(False)
        self.label_13.setObjectName("label_13")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/icon_info.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tabs.addTab(self.tab_info, icon, "")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_plot)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 20, 751, 381))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.vl_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.vl_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vl_3.setContentsMargins(0, 0, 0, 0)
        self.vl_3.setSpacing(0)
        self.vl_3.setObjectName("vl_3")
        self.lbl_busy_plot = QtWidgets.QLabel(self.tab_plot)
        self.lbl_busy_plot.setGeometry(QtCore.QRect(10, 190, 771, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_busy_plot.setFont(font)
        self.lbl_busy_plot.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_busy_plot.setObjectName("lbl_busy_plot")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/icon_graph.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tabs.addTab(self.tab_plot, icon1, "")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_log)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(80, 30, 635, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget_5.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget_5.setSizePolicy(sizePolicy)
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_2.setMinimumSize(QtCore.QSize(20, 0))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 4, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_5.setMinimumSize(QtCore.QSize(20, 0))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/icon_text.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tabs.addTab(self.tab_log, icon2, "")

        self.retranslateUi(tabs)
        tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tabs)

    def retranslateUi(self, tabs):
        _translate = QtCore.QCoreApplication.translate
        tabs.setWindowTitle(_translate("tabs", "Lowell Instruments\' BLE GUI"))
        self.lbl_ble_short.setText(_translate("tabs", "<bleshort>"))
        self.lbl_ble_long.setText(_translate("tabs", "<blelong>"))
        self.lbl_boatname.setText(_translate("tabs", "<boatname>"))
        self.lbl_internet.setText(_translate("tabs", "<internet>"))
        self.lbl_clock_time.setText(_translate("tabs", "<clocktime>"))
        self.lbl_clock_sync.setText(_translate("tabs", "<clocksync>"))
        tabs.setTabText(tabs.indexOf(self.tab_info), _translate("tabs", " Information"))
        self.lbl_busy_plot.setText(_translate("tabs", "..."))
        tabs.setTabText(tabs.indexOf(self.tab_plot), _translate("tabs", " Plots"))
        self.label_14.setText(_translate("tabs", " Last seen on"))
        self.label_16.setText(_translate("tabs", "-"))
        self.label_21.setText(_translate("tabs", "-"))
        self.label_18.setText(_translate("tabs", "MAC address"))
        self.label_4.setText(_translate("tabs", "-"))
        self.label_20.setText(_translate("tabs", "-"))
        self.label.setText(_translate("tabs", "-"))
        self.label_12.setText(_translate("tabs", "Logger name"))
        self.label_15.setText(_translate("tabs", "-"))
        self.label_17.setText(_translate("tabs", "-"))
        self.label_3.setText(_translate("tabs", "-"))
        self.label_19.setText(_translate("tabs", "-"))
        tabs.setTabText(tabs.indexOf(self.tab_log), _translate("tabs", "Log"))
